version: "3.8"
services:
  web:
    build: '.'
    ports:
      - 5000:5000
  
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
    ports:
      - $MONGODB_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db

volumes:
  db: